### ISSUE TITLE
Adding Flip Flop documentation to the circuit elements in documentation

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [CircuitVerse/CircuitVerseDocs#11]
As of now there is no documentation for different flip flops.

**Comment by NirmalKumarJoshi** [comment]
Can I work on this issue @satu0king ?

**Comment by Kedar-K** [comment]
I guess an issue was already raised on this topic by @satu0king, [check this out](https://github.com/CircuitVerse/CircuitVerseDocs/issues/1) and this is a [pull request](https://github.com/CircuitVerse/CircuitVerseDocs/pull/7) regarding this issue, and after some changes in this pull request as per requested by @satu0king We should be good to go. So @NirmalKumarJoshi you can probably work on other issues.

**Comment by agarwalrounak** [comment]
@satu0king This issue can be closed as duplicate!
