### ISSUE TITLE
Addition of prerequisite in the ReadMe file

### ISSUE THREAD

**Issue by Yash-Yadav** [CircuitVerse/CircuitVerseDocs#121]
#### I am submitting a - Addition in the ReadMe file.
* [] **Feature Request**

**Comment by Parikshit-Hooda** [comment]
@Yash-Yadav What's the progress on this?

**Comment by Yash-Yadav** [comment]
> 
> 
> @Yash-Yadav What's the progress on this?

Nothing till now!
But can use your help in identifying the per-requisites...
