### ISSUE TITLE
Improper Footer Redirect

### ISSUE THREAD

**Issue by monsij** [CircuitVerse/CircuitVerseDocs#126]
#### I am submitting a -
* [x] **Feature Request**

#### Describe your bug/feature -
Presently , when we click on the page footer links for the next and previous page, it takes us to a location other than the beginning of the required page.

#### Expected behaviour -
On clicking, it should take to the topmost part of the required page.

#### Screenshots (if relevant) -
![footer](https://user-images.githubusercontent.com/23289387/56041266-ef4e4c00-5d55-11e9-9d24-3c629207ddd6.PNG)

**Comment by Parikshit-Hooda** [comment]
@monsij Has any PR been made to fix this? If not done until now, this issue now under proposed GCI'19 participation.

**Comment by Shivansh2407** [comment]
Can I fix this?
