### ISSUE TITLE
GSOC 2019 Project  5

### ISSUE THREAD

**Issue by vinay72** [CircuitVerse/CircuitVerseDocs#13]
@satu0king According to the Official GSOC-2019 list of project ideas of CircuitVerse , there is project on : Create informative material for digital logic design,
Design interactive circuits.
DIY digital logic design E-book . I want to work on this Idea and want to take part in GSOC-2019 .

**Comment by Kedar-K** [comment]
@vinay72 This doesn't look like an issue in the current repository, for this, you can contact the mentor directly. I don't think so that there is a need to create a new issue for this.

**Comment by vinay72** [comment]
@Kedar-K Thanks for Replying.
