### ISSUE TITLE
Image not rendering - /docs/README.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerseDocs#133]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
The title image is not rendering.
![ccdocs](https://user-images.githubusercontent.com/25405707/67593665-51195500-f780-11e9-9851-636e5ecea81e.PNG)

#### Current behaviour -
The markdown instead, gets rendered - as can be seen above

#### Expected behaviour -
The image should render perfectly.

#### Are you working on this issue? (Yes/No)
No. Intended for GCI'19 under EASY.

**Comment by Parikshit-Hooda** [comment]
Related issue #134

**Comment by aayush-05** [comment]
Hey @Parikshit-Hooda !
I don't think the example given here is really a issue. The example you mentioned isn't an image but a simulator circuit which is running fine at the main website.
![image](https://user-images.githubusercontent.com/47032027/70072493-1cb97400-161d-11ea-9bcd-86ccc3a39fad.png)

**Comment by tachyons** [comment]
Closing as invalid
