### ISSUE TITLE
Image not linked properly

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerseDocs#134]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
The images [here](https://github.com/CircuitVerse/CircuitVerseDocs/blob/master/docs/export.md) don't render. 

#### Current behaviour -
The links are perhaps broken. Need eyes to fix this.

#### Expected behaviour -
The images should render alright.

#### Screenshots (if relevant) -
![ccdocsexport](https://user-images.githubusercontent.com/25405707/67594155-5fb43c00-f781-11e9-95b9-04efac4b01e9.PNG)

#### Are you working on this issue? (Yes/No)
No. Intended for GCI'19 under EASY.

**Comment by tachyons** [comment]
Markdown need not he properly rendered in github preview.
