### ISSUE TITLE
Contributor's Guide Needed in this repository.

### ISSUE THREAD

**Issue by vinay72** [CircuitVerse/CircuitVerseDocs#14]
@satu0king Can I add Contributor's Guide on How to Contribute to this Repository by sending a PR?

**Comment by Kedar-K** [comment]
@vinay72 Did you think of any content to put in contributors guide?

**Comment by vinay72** [comment]
@Kedar-K Yes, I would made a `Contributors.md` file if necessary.

**Comment by satu0king** [comment]
Also write instructions on how to test the docs offline, 
I use `python3 -m http.server`

**Comment by vinay72** [comment]
@satu0king Can you elaborate more on this like : how to write instructions on testing the docs offline as I have never worked on testing ?

**Comment by satu0king** [comment]
I meant manual testing, that is for the developer to check how the docs is actually rendered before being merged.

**Comment by Kedar-K** [comment]
@vinay72 You can also put extensions for some famous editors like **VScode, atom**, etc for the purpose of testing and even the HTTP server mentioned as mentioned by @satu0king.

**Comment by vinay72** [comment]
@Kedar-K Okay, I would do the required changes as soon as possible.
