### ISSUE TITLE
DARK MODE Error  

### ISSUE THREAD

**Issue by AnubhavMadhav** [CircuitVerse/CircuitVerseDocs#146]
#### I am submitting a -
* [] **Bug Report**

#### Screenshots (if relevant) - 
![Screenshot (1890)](https://user-images.githubusercontent.com/42323737/68077183-45afd480-fde5-11e9-95e6-8d2bb60c638f.png)

You can see in the Screenshot, that the "Dark Mode Button" is toggled on but still the site is in Light Theme. That's the issue.

**Comment by AnubhavMadhav** [comment]
Also, please look at the "Dark Mode Button":
When I switch dark mode on, it toggles.
But, after switching the dark mode on if I click on any of the button in the Navigation Bar, the "Dark Mode Button" toggles off, though Dark Mode is still on.

Expectation -"Dark Mode Button" should remain toggled on when user clicks on any of the button in the Navigation Bar, provided that user was already in the Dark Mode.

**Comment by harsha-iiiv** [comment]
Hey, @AnubhavMadhav we can label this issue for GCI-19

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is a part of Interactive Book repo and is already opened at https://github.com/CircuitVerse/Interactive-Book/issues/12

**Comment by fluctix** [comment]
Can i work on this?

**Comment by YashKumarVerma** [comment]
Solved.
