### ISSUE TITLE
Some elements fail to change color in dark mode

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerseDocs#147]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature -
When I switch the dark mode  on, I expect that everything inverts color according to the dark theme. But it fails in the case of multiplexer documentation.
#### Current behaviour -
Second input fails to change color.
#### Expected behaviour -
It should change color.
#### Screenshots (if relevant) -
![before](https://user-images.githubusercontent.com/42520146/68081634-630d8e80-fe37-11e9-9e85-e4eeebaa4248.PNG)
![after](https://user-images.githubusercontent.com/42520146/68081635-6739ac00-fe37-11e9-973e-4ac6b6808a2f.PNG)

**Comment by schezfaz** [comment]
Hey @YashKumarVerma, I would like to work on this issue. Can I take it forward?

**Comment by schezfaz** [comment]
Hey @YashKumarVerma, I would like to work on this issue! May I take it forward?

**Comment by schezfaz** [comment]
I have opened a PR for the same, please LMKWYT!
