### ISSUE TITLE
Fix navbar position

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerseDocs#152]
#### Describe your bug/feature - 
Currently, the position of navbar for mobile view is in the bottom left which is not expected and it overrides certain content of the docs too.

#### Screenshots (if relevant) - 
![45bbc5d1-5421-4f59-ad31-ea57f093a3e6](https://user-images.githubusercontent.com/44617923/68212446-8b47e980-ffff-11e9-9b4a-15f76cad7b79.png)

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
Already open at #139

**Comment by deepak2431** [comment]
@ShreyaPrasad1209 Thanks for the review. I will close it.
