### ISSUE TITLE
Misleading placement of dark mode toggle button and edit on github link

### ISSUE THREAD

**Issue by sachin235** [CircuitVerse/CircuitVerseDocs#154]
#### I am submitting a -
* [] **Feature Request**
* [] **UI-UX enhancement**

#### Current behaviour -
The "Edit on Github" link and the dark mode toggle button are placed simultaneously. Due to this the toggle button might be mistaken by the first time users, to be related to the "Edit on Github" link. 

#### Expected behaviour -
The "Edit on Github" and the toggle button should be placed separately.
The "Edit on Github" link should be placed on the left side.

#### Screenshots (if relevant) -
![Screenshot from 2019-11-06 00-33-10](https://user-images.githubusercontent.com/32926581/68237975-3d96a580-002e-11ea-97af-05883361a249.png)

#### Are you working on this issue? (Yes/No)
No. Intended for GCI19 under Easy.

**Comment by YashKumarVerma** [comment]
Closing in favour of the following workds
- #212 
- #213
