### ISSUE TITLE
Edit on Github redirects to the Readme

### ISSUE THREAD

**Issue by sachin235** [CircuitVerse/CircuitVerseDocs#155]
#### I am submitting a -
* [] **Feature Request**
* [] **Bug Report**

#### Current behaviour -
The "Edit on Github" link currently redirects to the Readme file of the master branch. 

#### Expected behaviour -
The "Edit on Github" link should instead redirect to the Github repository of CircuitVerseDocs.

#### Screenshots (if relevant) -
![Screenshot from 2019-11-06 00-47-56](https://user-images.githubusercontent.com/32926581/68238764-c8c46b00-002f-11ea-8742-5c6d7ef39b13.png)

#### Are you working on this issue? (Yes/No)
No. Intended for GCI19 under EASY.

**Comment by Parikshit-Hooda** [comment]
@sachin235 This issue can certainly be solved under GCI. Please provide steps to reproduce this issue. Where is this 'Edit on GIthub'(perhaps you can provide a screenshot for this as well so that we have more context)

**Comment by sachin235** [comment]
> @sachin235 This issue can certainly be solved under GCI. Please provide steps to reproduce this issue. Where is this 'Edit on GIthub'(perhaps you can provide a screenshot for this as well so that we have more context)

This "Edit on GitHub" is present on the home page of the CircuitVerseDocs itself. 

The screenshot 
https://user-images.githubusercontent.com/32926581/68237975-3d96a580-002e-11ea-97af-05883361a249.png

This should redirect to the CircuitVerseDocs repository instead of the Readme file of master branch.

**Comment by vibhuti019** [comment]
I would like to work on it.

**Comment by YashKumarVerma** [comment]
sure @vibhuti019

**Comment by nileshdas** [comment]
@vibhuti019 Working on this issue?

**Comment by vibhuti019** [comment]
Yes I am working on it.

**Comment by nileshdas** [comment]
Taking up this issue
