### ISSUE TITLE
Change complementary color of Dark Mode 

### ISSUE THREAD

**Issue by AnubhavMadhav** [CircuitVerse/CircuitVerseDocs#162]
#### I am submitting a -
* [x] **Feature Request**
* [] **Bug Report**

#### Describe your bug/feature -
Complementary color of Dark Mode is not much attractive currently. 
Click on this link https://docs.circuitverse.org/ and then toggle on the Dark Mode

#### Current behaviour -
Current color is RED with Dark Mode.
![Screenshot (1897)](https://user-images.githubusercontent.com/42323737/68334699-2d032f80-0101-11ea-8ede-9551dd69baf7.png)

#### Expected behaviour -
Color should be a bit attractive like Green or something else. The following Screenshot is in the Google Pixel 2 view.
![docs circuitverse org_(Pixel 2)](https://user-images.githubusercontent.com/42323737/68335072-cc282700-0101-11ea-8202-62fe77508aa6.png)

#### Screenshots (if relevant) - 
Uploaded

#### Are you working on this issue? (Yes/No)
Yes, I would like to

**Comment by YashKumarVerma** [comment]
I personally think that red is good, but at the same time, our logo is green in color, so why not our docs page?

**Comment by AnubhavMadhav** [comment]
> I personally think that red is good, but at the same time, our logo is green in color, so why not our docs page?

Yes, it can be.

**Comment by YashKumarVerma** [comment]
@AnubhavMadhav  are you willing to work on it ?

**Comment by AnubhavMadhav** [comment]
> @AnubhavMadhav are you willing to work on it ?

Not for now, got some other stuff to do, otherwise I would love to serve for CircuitVerse.

**Comment by schezfaz** [comment]
Can I work on this?

**Comment by nileshdas** [comment]
Can I work on this issue?

**Comment by nileshdas** [comment]
I am taking up this issue. Requesting reviews on this: https://nervous-kare-085e95.netlify.app/#/
@YashKumarVerma @Shivansh2407

**Comment by Shivansh2407** [comment]
Dark mode button is really a tedious task to click while in mobile view as the edit in GitHub  is close to dark mode button and when we click it, it opens GitHub for editing. Please fix that. Also while we are in desktop view, on clicking the dark mode button, it disappears. You need to fix that as well. Rest all looks good to me.
Please make a PR after fixing the mentioned changes @nileshdas 👍
