### ISSUE TITLE
button in the sidebar

### ISSUE THREAD

**Issue by JoshuaPoddoku** [CircuitVerse/CircuitVerseDocs#163]
#### I am submitting a -
* [x] **Feature Request**

#### Describe your bug/feature -
The button is placed at the bottom which is difficult to notice for a user.

#### Current behaviour -
The toggle button size is small and it is at the bottom.

#### Expected behaviour -
The button should be placed at the top and it should be increased in size.

#### Screenshots (if relevant) -
![screencapture-docs-circuitverse-org-2019-11-07-01_54_40](https://user-images.githubusercontent.com/31725457/68335612-cda61f00-0102-11ea-8389-73932dccd933.png)
`observe the bottom-left buttom`
#### Are you working on this issue? (Yes/No)
Yes, I would like to contribute!

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
Already open at #139

**Comment by JoshuaPoddoku** [comment]
Thanks. I'm sorry for that. Kindly check other
issues.

**Comment by ShreyaPrasad1209** [comment]
Sure, could you please close this issue?
