### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerseDocs#164]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature - 
Spelling mistake of a word. In the modifying elements section the word  choose is written as chose.

#### Screenshots (if relevant) -
![Screenshot from 2019-11-07 17-38-11](https://user-images.githubusercontent.com/44617923/68388060-cf64f680-0185-11ea-9cf0-15e6d9abb67a.png)

#### Are you working on this issue? (Yes/No)
No, this task is for GCI students.

**Comment by deepak2431** [comment]
@Parikshit-Hooda  Hi, this task fit into the task list of find and fix typos which you were looking for.
Thanks!

**Comment by arnoldpalmer42** [comment]
Hi there! Can I take this?

**Comment by Ansh0611** [comment]
Hi?
Can this be assigned to me?

**Comment by Shivansh2407** [comment]
@Ansh0611 go ahead and fix the typo.

**Comment by Ansh0611** [comment]
> @Ansh0611 go ahead and fix the typo.

Someone already fixed it

**Comment by Shivansh2407** [comment]
You can fix other issues @Ansh0611
