### ISSUE TITLE
Striped Truth Tables needs color improvements in dark mode.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerseDocs#167]
**Is your feature request related to a problem? Please describe.**

The tables on the docs page are too light in dark mode that the text is barely visible on them. So, please make the text darker in dark mode.

**Additional context**

![UI](https://user-images.githubusercontent.com/42115530/67973919-6b977680-fc37-11e9-8f80-70f02a6dfcc3.PNG)

**Comment by nileshdas** [comment]
Hi! Can I work on this issue?

**Comment by YashKumarVerma** [comment]
@nileshdas sure.

**Comment by nileshdas** [comment]
@YashKumarVerma the styling comes from unpkg.com CDNs which are not editable. Is there any other way around?

**Comment by YashKumarVerma** [comment]
can we use additional css styling for this @nileshdas ?

**Comment by nileshdas** [comment]
> can we use additional css styling for this @nileshdas ?
Can we use this?

![Screenshot (170)](https://user-images.githubusercontent.com/39062229/84744740-42163a00-afd1-11ea-9756-db972ab5ffe2.png)

**Comment by YashKumarVerma** [comment]
> > can we use additional css styling for this @nileshdas ?
> 
> Can we use this?
> Should I center align the binary digits?
> 
> ![Screenshot (170)](https://user-images.githubusercontent.com/39062229/84744740-42163a00-afd1-11ea-9756-db972ab5ffe2.png)

color improvements look good. Send pr.
