### ISSUE TITLE
Create a Parity Detector using Universal Gate

### ISSUE THREAD

**Issue by eKuG** [CircuitVerse/CircuitVerseDocs#168]
![2019-11-01 (1)](https://user-images.githubusercontent.com/33174166/68020308-15bce000-fcc4-11e9-9512-7d938a6f4fbd.png)
Parity detectors are used to find the error in the transmitted signal. Two types of Parity Detectors are there - Even and Odd
Also, add the limitations of using Parity Detector for Error Detection

**Comment by vibhuti019** [comment]
Explain the issue I would like to work on it.

**Comment by Ananthavijay** [comment]
@eKuG Please check this : https://circuitverse.org/simulator/edit/52999

**Comment by nileshdas** [comment]
Here's an idea:
We can embed circuits for 2, 3 and 4 bits and also show the Karnaugh map method for higher bits.

**Comment by YashKumarVerma** [comment]
@nileshdas please do
