### ISSUE TITLE
Favicon missing for CircuitVerse Docs

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerseDocs#169]
**Describe the bug**
The favicon icon is missing in the CircuitVerse Docs subpage.

**To Reproduce**
1. Go to 'https://docs.circuitverse.org/#/'
2. See error

**Expected behavior**
A proper favicon icon should be displayed for the CircuitVerse Docs page. Either the same CircuitVerse logo can be taken or a separate logo can be designed for the Docs section.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68533527-ed7e5280-034f-11ea-9183-88d2823cbfa6.png)

**Comment by fluctix** [comment]
a issue for this has already been made at https://github.com/CircuitVerse/CircuitVerseDocs/issues/135

**Comment by aayush-05** [comment]
Ok
