### ISSUE TITLE
No Home Button on Docs page

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerseDocs#170]
**Is your feature request related to a problem? Please describe.**
If a user wants to go back to the main CircuitVerse website after a series of viewing different pages on CircuitVerse Docs, he would have to go through all of them again when pressing the back button.

**Describe the solution you'd like**
A better solution would be to have a Home Button on each CircuitVerse Docs page to quickly redirect back to the main website.

**Comment by JoshHeng** [comment]
Hi, I've claimed this task on GCI

**Comment by JoshHeng** [comment]
Issue resolved, can close
