### ISSUE TITLE
Theme Toggler not working properly

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerseDocs#171]
**Describe the bug**
When the Dark theme mode is in, and the user switch pages on CircuitVerse Docs; the Theme Toggler gets back to its original state (i.e of Light theme) while the current theme is still Dark.

**To Reproduce**
1. Go to 'https://docs.circuitverse.org/#/'
2. Toggle the theme to Dark
3. Switch to any different page from the left sidebar

**Expected behavior**
The toggler should not come back to its original position when the pages are changed. It should clearly depict the current theme choice.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68534591-3e944380-035c-11ea-8813-c975d7e389e0.png)

![image](https://user-images.githubusercontent.com/47032027/68534598-481dab80-035c-11ea-85fc-72bddecdec4b.png)

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is a part of Interactive Book repo and is similiar to CircuitVerse/Interactive-Book#12

**Comment by aayush-05** [comment]
Okay

**Comment by aayush-05** [comment]
@ShreyaPrasad1209 This is a different issue.
The one you mentioned describes the fact that the Interactive book gets back to the light mode when the category is changed or the page is refereshed.
But in case of CircuitVerse Docs, the dark theme remains even after refreshing and only the toggler gets back to its initial position.

**Comment by satu0king** [comment]
I believe this is working now, please test it
@aayush-05 @ShreyaPrasad1209 

> But in case of CircuitVerse Docs, the dark theme remains even after refreshing and only the toggler gets back to its initial position.

For me however, the theme is not staying after refreshing.

**Comment by aayush-05** [comment]
For me currently, in CircuitVerse docs
Dark theme stays when switching pages but the toggler comes back to the original position. When the page is refreshed both the theme and the toggler gets reset.
In Interactive Book,
The theme is getting back to the light one on both switching pages and refreshing the page.

**Comment by YashKumarVerma** [comment]
This has been fixed.
