### ISSUE TITLE
Broken links in Modify.md file

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerseDocs#174]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -

There are broken image links in <a href="https://github.com/CircuitVerse/CircuitVerseDocs/blob/master/docs/Modify.md">Modify.md file</a> and <a href="https://github.com/CircuitVerse/CircuitVerseDocs/blob/master/docs/annotation.md">annotation.md</a>.

#### Current behaviour -

On clicking the accompanying link, it opens a 404 error page. 

#### Expected behaviour -

It should open the image in a new tab on clicking on the image or else should be a link to the related section of the doc.

#### Screenshots (if relevant) -

![broken links](https://user-images.githubusercontent.com/42115530/68964311-062eb280-07ff-11ea-8d20-20d693b1eb57.PNG)

#### Are you working on this issue? (Yes/No)
No. For GCI.

**Comment by satu0king** [comment]
@PragatiVerma18 The images are correctly rendered here https://docs.circuitverse.org/#/Modify
