### ISSUE TITLE
Prev and Next Links Missing

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerseDocs#176]
**Describe the bug**
The links to the previous and next links available at the bottom of the page are missing from the "Circuit Elements" and "Miscellaneous" page.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68967851-295d6000-0807-11ea-84bf-b6836957035c.png)

![image](https://user-images.githubusercontent.com/47032027/68967906-45610180-0807-11ea-9c11-d235c0e0f89e.png)

**Solution**
The div element showing the links should be set to a fixed display property for all of the pages of CircuitVerse Docs.

**Comment by shraddhavp** [comment]
ok I would like to add it

**Comment by chehak123** [comment]
I would like to work on it

**Comment by ShreyaPrasad1209** [comment]
I'm closing this issue as it's been resolved.
