### ISSUE TITLE
Dark Mode toggler overlapped

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerseDocs#177]
**Describe the bug**
After resizing the window size to 768px or less horizontally, the dark mode toggler gets overlapped by the Github corner logo. This makes it impossible to switch to dark mode. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68968951-c7eac080-0809-11ea-84bb-61035033dbe5.png)

**Solution**
Either the Dark mode toggler should be moved a little down or proper padding should be added to avoid overlapping.

**Comment by fluctix** [comment]
We can use https://edull24.github.io/fork-me-on-github/

**Comment by dkapur17** [comment]
There still seems to be an issue in mobile view.

![Overlapped-Slider-Issue](https://user-images.githubusercontent.com/37783178/75436469-a5c11c80-597a-11ea-96ec-456e5f691597.gif)

**Comment by aayush-05** [comment]
The pr by @mohit-003 is yet to be merged. Once merged, I think it will solve the bug for mobile devices as well.
