### ISSUE TITLE
Add CircuitVerse logo in the Readme

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerseDocs#182]
#### I am submitting a -
* [] **Feature Request** 

#### Describe your bug/feature -
Add the logo of CircuitVerse in the readme.

#### Are you working on this task -
No, this task is for GCI students.

**Comment by JoshHeng** [comment]
@sal2701 Please could you add this as a task on GCI

**Comment by sal2701** [comment]
@JoshHeng in the process. You can claim it in sometime.
