### ISSUE TITLE
docs server on localhost, not on 0.0.0.0:8000

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerseDocs#186]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
The server runs on localhost, not on 0.0.0.0 8000, as the readme says. Is this a docs problem, my system's problem or a bug exists?

#### Are you working on this issue? (Yes/No)
no

**Comment by JoshHeng** [comment]
I can't see any reference to `0.0.0.0` in the README.
For reference, `localhost`/`127.0.0.1` basically loops back to your computer. As you open the Python webserver on your computer and it opens port 8000 on your computer, when you go to `localhost:8000` this is what you visit

**Comment by ShubhankarKG** [comment]
Is this still relevant? Can be closed it seems @YashKumarVerma
