### ISSUE TITLE
Document Assignment Grading in Groups

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#190]
Add details on how a teacher can grade assignments. Describe the following

- [ ] Flow of control
- [ ] Different grading models

**Comment by ericsheng495** [comment]
https://docs.google.com/document/d/1DJXSMggqJYstkfYdSM7EaqKcsvNMT6NvyaiOOxQxAss/edit?usp=sharing

**Comment by deepak2431** [comment]
@ericsheng495 Hi, Can you please open a PR for it?
