### ISSUE TITLE
Dark Mode Slider

### ISSUE THREAD

**Issue by NumberC** [CircuitVerse/CircuitVerseDocs#199]
**Minor Bug**

#### Describe your bug/feature -
When you click the slider to change to dark mode, dark mode is active and so is the slider. However, when you navigate to another topic within the Docs, dark mode is still active, but the slider is not.

#### Current behaviour -
When you click the slider to change to dark mode, dark mode is active and so is the slider. However, when you navigate to another topic within the Docs, dark mode is still active, but the slider is not.

#### Expected behaviour -
When you click the slider to change to dark mode, dark mode is active and so is the slider. When you navigate to another topic within the Docs, dark mode is still active AND the slider is as well.

#### Screenshots (if relevant) -
![Capture](https://user-images.githubusercontent.com/47584014/71546559-13929d00-2966-11ea-9d06-60ca77842f1a.PNG)
![Capture2](https://user-images.githubusercontent.com/47584014/71546560-17262400-2966-11ea-9fdf-1eadfe71d001.PNG)

#### Are you working on this issue? (Yes/No)
No

**Comment by dkapur17** [comment]
Working on it.

**Comment by dkapur17** [comment]
Can this issue be closed?
