### ISSUE TITLE
Document Annotation Elements

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#2]

**Comment by developerbrandon** [comment]
On it :+1:

**Comment by Paritosh259** [comment]
[Document Annotation Elements.docx](https://github.com/CircuitVerse/CircuitVerseDocs/files/2922295/Document.Annotation.Elements.docx)

**Comment by sanctophagus** [comment]
Hey satu0king! I'd like to work on it, if no one is working on it.

**Comment by satu0king** [comment]
@sanctophagus go ahead
