### ISSUE TITLE
Documentation needed for Shift Registers.

### ISSUE THREAD

**Issue by vinay72** [CircuitVerse/CircuitVerseDocs#21]
@satu0king Documentation needed for these Digital Circuits known as Shift Registers which includes describing four  types of Shift Registers in a sequential manner.

**Comment by satu0king** [comment]
Hello, currently this documentation is for the use of circuit elements in the simulator. The interactive book project will have these sort of information.s

**Comment by vinay72** [comment]
@satu0king Okay, thanks for replying.
