### ISSUE TITLE
Function of toggle button not obvious

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerseDocs#212]
I am submitting a -
**Bug Report**

####Describe your bug/feature -
The toggle button in "Documentation" page has no description of what it does unless clicked. At first sight, looks as if it allows "Edit on Github" since it's next to it.

####To Reproduce
  Go to https://docs.circuitverse.org/#/
  See error

#### Expected behaviour -
Adding "Dark mode" next to the button improves appearance and user experience

#### Screenshots (if relevant) -
Before
![circuit15](https://user-images.githubusercontent.com/55310756/76865961-7458b400-6889-11ea-9816-b55f0ef6cb24.png)
My suggested fix
![circuit16](https://user-images.githubusercontent.com/55310756/76865996-8175a300-6889-11ea-944e-592f313725d1.png)

#### Are you working on this issue? (Yes/No)
Yes, I would like to take this up

**Comment by Vishruth-S** [comment]
@Ananthavijay Could you please tell me where can I find the source code of this page so as to make the above change

**Comment by Ananthavijay** [comment]
I think [this](https://github.com/CircuitVerse/CircuitVerseDocs/blob/master/docs/index.html) is the file you should edit.
