### ISSUE TITLE
overflow at phone, and tablet screens on Getting started page

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerseDocs#215]
#### I am submitting a -
* [X] **Bug Report**

#### Current behaviour -
Getting started videos or gifs width overflow at phone, and tablet screens

#### Expected behaviour -
Each gif or video should take 100% width

#### Screenshots (if relevant) -
![docs](https://user-images.githubusercontent.com/41790090/77384358-df285480-6d8d-11ea-933b-4e8fb07ac971.gif)

#### Are you working on this issue? (Yes/No)
NO

**Comment by Umoren** [comment]
YES I AM WORKING ON THIS
