### ISSUE TITLE
CircuitVerse logo redirects to itself

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerseDocs#217]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
The CircuitVerse logo at the top left of page redirects to learn.circuitverse.org which is not good if i come from CircuitVerse's website.

#### Current behaviour -
The link on top left redirects to learn.circuitverse.org

#### Expected behaviour -
The link on top left redirects to circuitverse.org

#### Screenshots (if relevant) -
![Screenshot from 2020-03-25 18-21-17](https://user-images.githubusercontent.com/50791000/77538289-7e9c3300-6ec5-11ea-835f-1caea3425592.png)

#### Are you working on this issue? (Yes/No)
Yes

**Comment by coding-CEO** [comment]
@ShubhankarKG this issue does not belong to this repo.
You can close this issue.
