### ISSUE TITLE
Navigation issue between Official Page and documentation page

### ISSUE THREAD

**Issue by coding-CEO** [CircuitVerse/CircuitVerseDocs#222]
Issue is,
from https://learn.circuitverse.org/ you Can go to https://circuitverse.org/
but,
from https://docs.circuitverse.org/#/  There is no way to go to https://circuitverse.org/

Anyone can take this issue.

**Comment by schezfaz** [comment]
Hey, I would like to work on this issue! I have forked the project, and was thinking we could add the logo (as on https://learn.circuitverse.org/) that redirects it back to https://circuitverse.org/  above the search tab. Can I take this forward if possible?

**Comment by coding-CEO** [comment]
> Hey, I would like to work on this issue! I have forked the project, and was thinking we could add the logo (as on https://learn.circuitverse.org/) that redirects it back to https://circuitverse.org/ above the search tab. Can I take this forward if possible?

Sure. you can do this.
Best of luck.

**Comment by schezfaz** [comment]
Thankyou, could you please assign this issue to me?

**Comment by coding-CEO** [comment]
> Thankyou, could you please assign this issue to me?

I don't have the authority to do that.
I think @YashKumarVerma Will assign this issue to you.

**Comment by schezfaz** [comment]
I think this issue is already been dealt with as per: #188.

**Comment by YashKumarVerma** [comment]
> I think this issue is already been dealt with as per: #188.

Could you help me understand how?
I think it's still unresolved as 
- we cannot go to circuitverse.org from docs
- closely linked to #206 


Read https://github.com/CircuitVerse/CircuitVerseDocs/issues/206#issuecomment-633653912 for more context. We should fix this for once.

**Comment by vibhuti019** [comment]
i would like to work on this issue.

**Comment by vibhuti019** [comment]
We can give a link to CircuitVerse above search

**Comment by CapTen101** [comment]
Hi @YashKumarVerma I want to work on this issue.
- I saw you comment in #206 PR mentioning that the heading will always remain a hyperlink for content level access.
- We can simply write `CircuitVerse` in place of `CircuitVerse Documentation` and point it to https://circuitverse.org/ since `home` already does that job for us by pointing to the Home page of documentation: https://docs.circuitverse.org/#/?id=welcome-to-circuitverse

**Comment by gaurivn** [comment]
Is this issue available? If yes, I would like to work on it

**Comment by CapTen101** [comment]
@gaurivn Hi. Actually I'm still working on this

**Comment by gaurivn** [comment]
Okay

**Comment by YashKumarVerma** [comment]
@CapTen101  please send a pr as soon as you can. because this was practically stale for all this time

**Comment by CapTen101** [comment]
Ok, sure @YashKumarVerma

**Comment by palak199** [comment]
is it open yet?

**Comment by ruhci28** [comment]
Hii, @YashKumarVerma can I take this issue.?

**Comment by YashKumarVerma** [comment]
Yes, it's still open .

**Comment by ruhci28** [comment]
Hii @YashKumarVerma  I made these changes.
![Aug-16-2020 23-14-53](https://user-images.githubusercontent.com/59759735/90340588-e68b1b80-e016-11ea-9162-60bd396a89da.gif)
