### ISSUE TITLE
testbench.mp4 file is not found in testbench docs

### ISSUE THREAD

**Issue by animesh-007** [CircuitVerse/CircuitVerseDocs#228]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
Testbench.mp4 file not found

#### Current behaviour -
testbench.mp4 file is not found in testbench docs
#### Expected behaviour -
adding testbench.mp4 file as testbench.gif in testbench docs

#### Are you working on this issue? (Yes/No)
yes

**Comment by YashKumarVerma** [comment]
any updates @animesh-007
