### ISSUE TITLE
Dark mode button broken :(

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerseDocs#229]
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature - 
The Dark mode button is broken :(

#### Current behaviour -
The dark mode button changes to a non visible input button

#### Expected behaviour -
The previously used dark mode button toggle worked fine

#### Screenshots
![Screenshot from 2020-05-21 16-53-46](https://user-images.githubusercontent.com/50791000/82554500-b2bd6880-9b83-11ea-9fc7-6c7c16965d2e.png)
![Screenshot from 2020-05-21 16-53-49](https://user-images.githubusercontent.com/50791000/82554503-b51fc280-9b83-11ea-83e4-fc26826ed7f0.png)

#### Are you working on this issue? (Yes/No)
I guess this is a commit that needs to be reverted.

**Comment by Shivansh2407** [comment]
@YashKumarVerma
