### ISSUE TITLE
Github pages give 404 on refresh

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerseDocs#231]
#### I am submitting a -
* [ ] **Feature Request**
* [x] **Bug Report**

#### Describe your bug -
All pages except the home page give a 404 error on refresh.

#### Current behaviour -
As stated, only the main page works on refresh. No other pages work.

#### Expected behaviour -
All pages work the same on refresh.

#### Screenshots (if relevant) -
![Screenshot from 2020-05-22 12-19-58](https://user-images.githubusercontent.com/50791000/82639544-945c7900-9c26-11ea-8046-2220156b9d40.png)
![Screenshot from 2020-05-22 12-20-02](https://user-images.githubusercontent.com/50791000/82639548-97576980-9c26-11ea-977d-86470170f90d.png)

#### Are you working on this issue? (Yes/No)
This is a high priority issue as far as UX is concerned. All suggestions are welcome.

**Comment by Umoren** [comment]
Yes, i'm working on this.
