### ISSUE TITLE
Outdated reference in README

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/CircuitVerseDocs#238]
The outdated information should be either updated/removed.

**Comment by CapTen101** [comment]
Can I take up this issue? @YashKumarVerma

**Comment by YashKumarVerma** [comment]
Sure

**Comment by CapTen101** [comment]
Cool, thanks!

**Comment by CapTen101** [comment]
Hi @YashKumarVerma. Can you please throw some light as to what are some outdated references in the Readme excepe the changing gsoc 2019 reference to gsoc 2020? thanks! :smile:

**Comment by YashKumarVerma** [comment]
Hint, something regarding gsoc.
.

**Comment by CapTen101** [comment]
right

**Comment by CapTen101** [comment]
Hi @YashKumarVerma, kindly review the above mentioned PR. :smile:
