### ISSUE TITLE
Installation In Heroku Can Also Be Added In ReadME.md

### ISSUE THREAD

**Issue by vibhuti019** [CircuitVerse/CircuitVerseDocs#241]
#### I am submitting a -
* [] **Feature Request**
We can add installation in Heroku also in ReadME.md

**Comment by YashKumarVerma** [comment]
> #### I am submitting a -
> * [] **Feature Request**
>   We can add installation in Heroku also in ReadME.md

we can add, but why would someone try to redeploy circuitverse documentation on a dyno?

**Comment by vibhuti019** [comment]
For developement purpose we can use Heroku as heroku can used from CLI.
