### ISSUE TITLE
Update wire section 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerseDocs#242]
#### I am submitting a -
* [x] **Feature Request**

#### Describe your bug/feature -
update connecting wires section https://docs.circuitverse.org/#/getting_started?id=connecting-wires
with this new feature 
https://github.com/CircuitVerse/CircuitVerse/pull/1351
#### Are you working on this issue? (Yes/No)
NO

**Comment by Umoren** [comment]
Yes

**Comment by CapTen101** [comment]
Can I work on this issue @mahmodHammad since #246 doesn't addresses the required feature update?

**Comment by mahmodHammad** [comment]
@CapTen101 sure, if  @Umoren didn't respond within the next 24 hours

**Comment by CapTen101** [comment]
Ok, cool :+1: @mahmodHammad

**Comment by CapTen101** [comment]
@mahmodHammad  Also, just to clear both the options (dragging node & ctrl+click) only a single video is fine for demonstration since both method produce the same output?

**Comment by mahmodHammad** [comment]
No
CTRL + Clicks is for creating multiple nodes as you want until you reach an other node or wire.
Dragging can only create one node, so in some cases if there's a distence between the destination you have to drag, drop multiple times

**Comment by CapTen101** [comment]
Oh right @mahmodHammad . I just confirmed it too with the simulator :+1:

**Comment by mahmodHammad** [comment]
Ctrl, click make it possible to draw long wires easily

Dragging is easier for drawing short wires.

Take a look at the gif inside the PR you will notice the difference, or try it yourself 🙂


So we need 2 videos you make multiple nodes(angles) to let user distinguish the difference

**Comment by CapTen101** [comment]
Yes I just tried it in the simulator and noticed the difference immediately. Thanks for heads-up :smile:

**Comment by Umoren** [comment]
Oh I misunderstood the issue
I wanted to create a new issue because, on the Getting Started page, the drag video was duplicated.
@CapTen101 you can continue with this.
I will create the issue.

**Comment by CapTen101** [comment]
ok, thanks @Umoren
