### ISSUE TITLE
Documentation for RGB Led Matrix

### ISSUE THREAD

**Issue by nileshdas** [CircuitVerse/CircuitVerseDocs#260]
## Is your feature request related to a problem? Please describe.
RGB Led Matrix documentation is missing. Adding it would help users as it is a bit confusing.

## Are you working on this? (Yes/No)
Yes

**Comment by CapTen101** [comment]
Its already been worked on in. This is duplicate issue. Reference  [issue #128](https://github.com/CircuitVerse/CircuitVerseDocs/issues/128) and a PR is already opened againts it. @nileshdas

**Comment by nileshdas** [comment]
Thanks for pointing out!

**Comment by CapTen101** [comment]
You can close this issue @nileshdas

**Comment by YashKumarVerma** [comment]
Closign in favour of https://github.com/CircuitVerse/CircuitVerseDocs/issues/128
