### ISSUE TITLE
Adding Documentation for embedding circuits for new contributors

### ISSUE THREAD

**Issue by CapTen101** [CircuitVerse/CircuitVerseDocs#262]
## Is your feature request related to a problem? Please describe.
Currently there's no documentation as to how circuits should be embedded in the documentation for new contributors. I too felt the need of it when I started.

## Describe the solution you'd like
writing a separate section describing steps for the same

**Comment by nileshdas** [comment]
This has been worked upon in PR #97 .

**Comment by CapTen101** [comment]
That PR hasn't been merged and that user is deleted. See carefully there, it's a 'ghost' user. Github marks those users as ghost who have their account decativated
