### ISSUE TITLE
A good Introduction needed in the Official Readme.md 

### ISSUE THREAD

**Issue by vinay72** [CircuitVerse/CircuitVerseDocs#27]
#### I am submitting a -
* **Feature Request**

#### Are you working on this issue? (Yes/No)
Yes

**Comment by agarwalrounak** [comment]
I don't think it is needed! Everything(including introduction) is meant to be read online at https://docs.circuitverse.org/ which lies inside the `docs` repository

**Comment by satu0king** [comment]
I am going to add the contributing guidelines as there seems to be a lot of confusion regarding the readme, the purpose of this repo and how to contribute.
