### ISSUE TITLE
The numbering of ways to connect wires between elements of the circuit always shows 1. 

### ISSUE THREAD

**Issue by ineffable23** [CircuitVerse/CircuitVerseDocs#279]
## Screenshots/GIFs
If applicable, add screenshots or GIFs to help explain your problem.

**Comment by Shivansh2407** [comment]
Please Explain the issue in detail , supporting it with screenshots and Links

**Comment by pranay-simejia** [comment]
@Shivansh2407 numerical bullet point on [connecting](https://docs.circuitverse.org/#/getting_started?id=connecting-wires) should be 2.

**Comment by Shivansh2407** [comment]
Fixed in #282
