### ISSUE TITLE
Timing Diagram does not turn green in clicking like all others

### ISSUE THREAD

**Issue by musk101** [CircuitVerse/CircuitVerseDocs#283]
## Describe the bug
When you click on timing diagram on the left navbar it does open bit it's color does not change to green like all other elements.

## To Reproduce
1. Go to 'HTML file'
2. Check timing diagram and fix the bug
3. See error

## Expected behavior
The timing diagram on being clicked should change to green color like all others.

## Screenshots/GIFs
![image](https://user-images.githubusercontent.com/61506798/104313542-2c80d880-54fe-11eb-908c-ae2121478b8f.png)

## Device Information [optional]:
 - Browser [ chrome]
 - OS [Windows 10]

**Comment by Preeti2095** [comment]
I want to work on this issue.

**Comment by Shivansh2407** [comment]
Hey @musk101 @Preeti2095 , CV Docs are undergoing a transformation as a Part of GSoD 2020 Program and we will be soon merging it to the master. Till then you can look for other issues in various other repositories of CircuitVerse. Happy Contributing 🎉

**Comment by Preeti2095** [comment]
All the best for GSoD😊😊💥💥
