### ISSUE TITLE
Menu icon not translucent and search bar position not fixed.

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerseDocs#290]
## Describe the bug
Menu icon's div is translucent.

## To Reproduce
1. Go to 'https://docs.circuitverse.org/#/outputs'
2. See error

## Expected behavior
Search bar should be fixed adjacent to the menu icon for better UX.

##Relevant screenshots.
![image](https://user-images.githubusercontent.com/70064696/112446094-d9d16180-8d75-11eb-9cf4-0efa32d07f08.png)

## Are you working on this issue? (Yes/No)
Yes.

**Comment by Shivansh2407** [comment]
@pranay-simejia we need to merge GSOD work before merging anymore PRs. Please have a look at #282 , set it up in your PC and let us know if it has some issues. We'll be merging it soon. Thank you 👍

**Comment by ShreyaPrasad1209** [comment]
@pranay-simejia I tried to reproduce but could not see this issue 😕

**Comment by pranay-simejia** [comment]
@ShreyaPrasad1209 did you scroll down the sidebar?

**Comment by khairnarsaurabh23** [comment]
@pranay-simejia  is issue is solved?
or else i can work on this issue?

**Comment by Palaksharma23** [comment]
i want to work on this issue , can i take this up
