### ISSUE TITLE
TestBench links not working

### ISSUE THREAD

**Issue by anmolkohli13** [CircuitVerse/CircuitVerseDocs#293]
## Describe the bug
The links in the testbench section are not working and when you click on the link for the guide for using the testbench it takes you to https://www.godaddy.com/forsale/circuitverse.com and asks to buy the domain. Also when visiting https://circuitverse.org/testbench there is an error and the page is not displayed.

## To Reproduce
1. Go to https://docs.circuitverse.org/#/testbench
2. Click on the links for accessing testbench
3. See the errors

## Expected behavior
The links should take you to the respective page of testbench which right now is https://circuitverse.org/testbench.html 

## Screenshots/GIFs
If applicable, add screenshots or GIFs to help explain your problem.

## Device Information [optional]:
 - OS: Windows
 - Browser : Chrome
 - Version 89

## Additional context
The testbench is yet to be constructed but the links provided on the docs page should take you to the page assigned or display a message until the page is deployed about the feature being developed.

## Are you working on this issue? (Yes/No)
No

**Comment by Shivansh2407** [comment]
Please have a look at #282 , Set it up in your local machine and let us know if you face any issues! It is the updated version of the CircuitVerse Docs which will be merged soon. Thank you for your efforts 👍
