### ISSUE TITLE
Document Input Elements

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#3]
You will need to illustrate the various options of individual components and how to use it on CircuitVerse. Tips and tricks will be helpful. 

- [ ] Input
- [ ] Button
- [ ] Ground
- [ ] Power
- [ ] Constant 
- [ ] Stepper 
- [ ] Random
- [ ] Counter

![image](https://user-images.githubusercontent.com/2092958/54450825-5be62300-4777-11e9-8c6e-952f4863e088.png)

**Comment by jeel2308** [comment]
can you explain it briefly?

**Comment by satu0king** [comment]
Checkout Input elements of the simulator at circuitverse.org/simulator. Some of them are Button, Power, Ground. So the usage of these elements needs to be documented for docs.circuitverse.org

**Comment by Kedar-K** [comment]
@satu0king I will work on this.

**Comment by Kedar-K** [comment]
#12 Created docs successfully @satu0king. Please let me know if some changes required.

**Comment by Kedar-K** [comment]
Requested changes made @satu0king .

**Comment by Parikshit-Hooda** [comment]
@satu0king close this issue, please.

**Comment by Ananthavijay** [comment]
@nitin10s This issue can be closed.
