### ISSUE TITLE
Make the sidebar more responsive for smaller width phone like new fold phones

### ISSUE THREAD

**Issue by AFZL210** [CircuitVerse/CircuitVerseDocs#338]
## Is your feature request related to a problem? Please describe.
the sidebar text is not visible in smaller width smartphones

## Describe the solution you'd like
the sidebar can be fixed with simple media query by reducing the font size a little, without disturbing the alignment of other components.

## Describe alternatives you've considered
instead of reducing the font size we can increase the width of sidebar container also.

## Additional context
Video
![](https://res.cloudinary.com/primeflix/image/upload/v1673443714/ezgif.com-gif-maker_npy4yz.gif)

## Are you working on this? (Yes/No)
No

**Comment by ksba2004** [comment]
Yes, I would like to work on this.
Please assign this to me.

**Comment by anishbasnet027** [comment]
I want to work on this issue please assign me.

**Comment by vikaskumar2703** [comment]
can i help in solving this issue?

**Comment by AFZL210** [comment]
@vikaskumar2703 yes sure go ahead
