### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by monsij** [CircuitVerse/CircuitVerseDocs#34]
#### I am submitting a -
* [ ] **Feature Request**
* [x] **Bug Report**

guage --> gauge

#### Screenshots (if relevant) -
![gauge](https://user-images.githubusercontent.com/23289387/54472595-c8e9cf00-47f0-11e9-98a9-f50e6b3fcb60.JPG)

#### Are you working on this issue? (*Yes*)
I am interested to fix this, but as the Wiki is not directly editable, I think it has to be done on the maintainer side itself.

**Comment by satu0king** [comment]
Thank you
