### ISSUE TITLE
Change the image of CircuitVerse forum with new UI

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerseDocs#344]
## Describe the bug
In the Introduction of the docs, the attached image of CircuitVerse Forum is of the previous UI which has been changed recently.

## To Reproduce
1. Go to 'https://docs.circuitverse.org/#/chapter1/1introduction'
2. Scroll down to 'Figure 1.3:'
4. See the error

## Expected behavior
Update the image with the new UI.

## Screenshots/GIFs
![image](https://user-images.githubusercontent.com/89515816/221622453-c7a1bb97-c3c7-4d2f-9401-9c20b7be9b09.png)

## Additional context
This feature is under the fosshack, you need to register [here](https://fossunited.org/login#login). You can join #fosshack-students channel in slack for any doubts and support

## Are you working on this issue? 
No

**Comment by vikaskumar2703** [comment]
can i be assigned on this issue

**Comment by vedant-jain03** [comment]
@vikaskumar2703 Sure, go ahead!

**Comment by Adarsh9306** [comment]
Hey @Prerna-0202 
if the issue is still open can you please assign it to me?

**Comment by vikaskumar2703** [comment]
close this issue

**Comment by Prerna-0202** [comment]
Fixed in #346
