### ISSUE TITLE
Edit https://github.com/CircuitVerse/CircuitVerseDocs/edit/master/docs/chapter7/3testcircuits.md

### ISSUE THREAD

**Issue by zzz-creator** [CircuitVerse/CircuitVerseDocs#350]
## Describe the solution you'd like
We can add a sequential test example here: https://github.com/CircuitVerse/CircuitVerseDocs/edit/master/docs/chapter7/3testcircuits.md

**Comment by Adarsh9306** [comment]
Hey @zzz-creator if the issue is still open can you please assign it to me?

**Comment by loydlobo7** [comment]
I can work on this if the issue is open can you please assign it to me

**Comment by zzz-creator** [comment]
What the f*** are these replies?!
