### ISSUE TITLE
CV Marketing video is not showing at the end of Chapter 1 Introduction

### ISSUE THREAD

**Issue by Nitishupkr** [CircuitVerse/CircuitVerseDocs#353]
## Describe the bug
At  the end of the introduction of the chapter 1 the cv marketing video is not showing its blank

## To Reproduce
1. Go to 'https://docs.circuitverse.org/#/chapter1/1introduction'
3. Scroll down to 'end'

## Screenshots/GIFs
![circuitverse](https://user-images.githubusercontent.com/95420063/236444655-0961d62f-98a0-45e5-ac1a-817e7271ed0a.png)

## Are you working on this issue? (Yes/No)
Yes

**Comment by Nitishupkr** [comment]
check it ones @Prerna-0202

**Comment by Jay-sanjay** [comment]
@Nitishupkr is the issue resolved

**Comment by Murdock9803** [comment]
@Nitishupkr looks like the issue has not been solved yet...
 @Prerna-0202 @tanmoysrt I would like to work on the issue.

**Comment by Murdock9803** [comment]
@Prerna-0202 @tanmoysrt I worked on the issue as no one was working on it since months. Please review my PR.
