### ISSUE TITLE
MSB and LSB miss-documentation

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerseDocs#39]
The MSB and LSB components are using an input connected to their ENABLE pin, but the ENABLE pin is an output (active when the input is non-zero). This should be fixed ASAP.

**Comment by fdila** [comment]
I'm working on it

**Comment by satu0king** [comment]
@jbox144 can you confirm if this is correct?

**Comment by jbox144** [comment]
> @jbox144 can you confirm if this is correct?

I can link you to a project where this functionality is used

https://circuitverse.org/users/1577/projects/5829

Admittedly, labeling the pin EN is a bit confusing, as EN would normally be an input.

**Comment by satu0king** [comment]
No, the documentation has been updated. Can you confirm if it is correct now?

**Comment by jbox144** [comment]
> No, the documentation has been updated. Can you confirm if it is correct now?

Close. The EN output is active when the delector is getting a non-zero value. But for all intensive purposes, it's accurate.
