### ISSUE TITLE
Document Output Elements

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#4]
You will need to illustrate the various options of individual components and how to use it on CircuitVerse. Tips and tricks will be helpful. 

- [ ] Output
- [ ] RGBLed
- [ ] LED
- [ ] VariableLed
- [ ] HexDisplay
- [ ] SevenSegmentDisplay
- [ ] SixteenSegmentDisplay 
- [ ] SquareRGBLed

![image](https://user-images.githubusercontent.com/2092958/54450892-7f10d280-4777-11e9-9c33-9e72d0fc2ea6.png)

**Comment by NirmalKumarJoshi** [comment]
@satu0king  I would like to work on this issue. 
Tell me how to go ,

**Comment by Kedar-K** [comment]
Is anyone working on this issue, I would like to proceed with this issue. @NirmalKumarJoshi , @satu0king.

**Comment by Paritosh259** [comment]
[Document Output Elements.md](https://github.com/CircuitVerse/CircuitVerseDocs/files/2922289/Document.Output.Elements.docx)

**Comment by sanctophagus** [comment]
Hey @satu0king I'd like to work on this issue, if no one is working on it.
