### ISSUE TITLE
Document RAM, ROM, EEPROM

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#46]
Create a page called memory elements and add documentation for these

- [ ] ROM
- [ ] RAM
- [ ] EEPROM

Helpful links

https://github.com/CircuitVerse/CircuitVerse/pull/229
https://github.com/CircuitVerse/CircuitVerse/pull/113

**Comment by harsha-iiiv** [comment]
I would like to work on this issue. Please assign to me @satu0king .

**Comment by satu0king** [comment]
Sure, please start a PR with WIP to claim the issue.

**Comment by harsha-iiiv** [comment]
👍

**Comment by theredcap** [comment]
@harsha-iiiv I see that you have not opened a pull request since 2 days. As I was working on documentation for sequential elements I had already made the documentation for ROM. I just saw this isuue and have created a WIP pull request as per the requirements. Are you still working on this?

**Comment by theredcap** [comment]
@harsha-iiiv awesome, I shall close my pull request then.
