### ISSUE TITLE
Image link was broken

### ISSUE THREAD

**Issue by harsha-iiiv** [CircuitVerse/CircuitVerseDocs#49]
#### I am submitting a -
 * [] **Bug Report**

#### Describe your bug/feature -
Image links were broken in 'Test Bench'  

#### Current behaviour -
Not displaying any images
#### Screenshots (if relevant) -
![Screenshot (45)](https://user-images.githubusercontent.com/31560965/54865344-2dc19e00-4d8a-11e9-9c79-9f69beae74d7.png)

#### Are you working on this issue? (Yes/No)
         No

**Comment by satu0king** [comment]
The issue was just resolved.
