### ISSUE TITLE
Live Circuit block not visible on small screens

### ISSUE THREAD

**Issue by harshagrwl** [CircuitVerse/CircuitVerseDocs#51]
#### I am submitting a -
* [] **Bug Report**

#### Describe your bug/feature -
The live circuit and video block is not completely visible on small screens.
#### Current behaviour -
When the webpage is viewed on small screens( for example mobile phones), the live circuit and video block goes out of the screen and creates a poor user interface for the page.
#### Expected behaviour -
The video or the live circuit block should be completely visible to all the users on all screen sizes. 
#### Screenshots (if relevant) -
![WhatsApp Image 2019-03-23 at 7 05 21 PM](https://user-images.githubusercontent.com/43218240/54866824-b64a3980-4d9e-11e9-82c3-9ae9046b049a.jpeg)

#### Are you working on this issue? (Yes/No)
Yes

**Comment by harshagrwl** [comment]
#52 will close this issue

**Comment by satu0king** [comment]
If the circuit can be made to take less space on small screens and same space on large screens, then we can have a solution.
