### ISSUE TITLE
Documentation for Sequential Circuits

### ISSUE THREAD

**Issue by theredcap** [CircuitVerse/CircuitVerseDocs#60]
#### I am submitting a -
* [ ] **Feature Request**
I am adding the documentation of the sequential circuits.

#### Describe your bug/feature -
It will provide a brief introduction to the Sequential Circuit element of the Simulator.
#### Current behaviour -
Currently there is no documentation for the Sequential Circuits
#### Screenshots (if relevant) -
![Screenshot_2019-03-24 Home - CircuitVerse Docs](https://user-images.githubusercontent.com/42991063/54884740-9731d180-4e9c-11e9-9902-e6d4f711817b.png)
I am currently working on this.
#### Are you working on this issue? (Yes/No)
Yes

**Comment by Asritha57135** [comment]
I am good at the topic sequential circuits and really want to work on this issue could you please tell me where to start and how...

**Comment by theredcap** [comment]
@Asritha57135 Hi, I am working on this issue. Maybe you could help to solve other issues in the documentation. For starting to contribute to other issues simply open a pull request referencing those issues. In order to reference an issue you should use the keywords like Fixed #[Issue Number].

You can also open up a new issue, explaining the things you'd like to add to the documentation, like I did with this issue and then work on it. Feel free to reach out if you have any queries.
