### ISSUE TITLE
Documentation for test benches 

### ISSUE THREAD

**Issue by monsij** [CircuitVerse/CircuitVerseDocs#62]
#### I am submitting a -
* [x] **Feature Request**

#### Describe your bug/feature -
The current documentation does not addresses test benches.

#### Major milestones ####
- [ ] Test bench input
- [ ] Test bench output

**Comment by satu0king** [comment]
Check this https://circuitverse.org/testbench for creating the documentation

**Comment by monsij** [comment]
@satu0king  Can you provide me a simple circuit implementing the test bench. As in, I tried to test a design using it but I am unable to understand the function of the left port of `TB_input`. An example would help me out.
