### ISSUE TITLE
Adding Subtractor (half and full) docs

### ISSUE THREAD

**Issue by saumyashrm2802** [CircuitVerse/CircuitVerseDocs#71]
#### I am submitting docs on -
* [] **Half subtractor**
* [] **Full subtractor**

#### Are you working on this issue? (Yes/No)
YES

**Comment by saumyashrm2802** [comment]
@armudgal @satu0king please assign me this issue

**Comment by satu0king** [comment]
This repository is to document CircuitVerse features not digital design concepts
