### ISSUE TITLE
Adding magnitude comparator (4 bit) 

### ISSUE THREAD

**Issue by saumyashrm2802** [CircuitVerse/CircuitVerseDocs#72]
#### I am submitting a -
*  **Feature Request**

#### Describe your feature -
I will add docs on 4 bit magnitude or equality comparator usiing XNOR and AND gates.

#### Are you working on this issue? (Yes/No)
YESS

**Comment by satu0king** [comment]
This repository is to document CircuitVerse features not digital design concepts
