### ISSUE TITLE
HTML <input> Tag

### ISSUE THREAD

**Issue by quangpro1610** [CircuitVerse/CircuitVerseDocs#8]
The <input> tag specifies an input field where the user can enter data.
<input> elements are used within a <form> element to declare input controls that allow users to input data.
An input field can vary in many ways, depending on the type attribute.

Read more: https://www.w3schools.com/tags/tag_input.asp

**Comment by satu0king** [comment]
I don't get what the issue is really about? Could you elaborate more?
