### ISSUE TITLE
Document groups, assignments 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerseDocs#9]
- [ ] How to create groups, add students
- [ ] How to create assignments, set deadline etc
- [ ] Instructions for students

**Comment by vinay72** [comment]
@satu0king We can make a platform like a Web App for these things where all the students can come together and join the Group and Assignments would be given with a Deadline . When a Student joins the group he/she would be given Instructions on how to proceed further.

**Comment by agarwalrounak** [comment]
I am working on those issue.

**Comment by iamNamanKhare** [comment]
I think, no one is working on this issue. So, I am taking up this Issue.

**Comment by agarwalrounak** [comment]
@iamNamanKhare Go ahead! I was supposed to work on this but couldn't do so due to other commitments.

**Comment by iamNamanKhare** [comment]
@agarwalrounak okay!!
