### ISSUE TITLE
Documentation for TTY

### ISSUE THREAD

**Issue by harsha-iiiv** [CircuitVerse/CircuitVerseDocs#94]
#### I am submitting a -
* [] **Feature Request**
 

 
 

#### Are you working on this issue? (Yes/No)
Yes

**Comment by theredcap** [comment]
@harsha-iiiv @satu0king As TTY and keyboard are placed under sequential element, it would be better if we could merge this documentation with the one I made for sequential elements. Also the file here is named as sequential.md this may create naming conflicts. What are your opinions?

**Comment by harsha-iiiv** [comment]
Agreed @theredcap
