### ISSUE TITLE
Real Time Chat feature needed in Docs.

### ISSUE THREAD

**Issue by vinay72** [CircuitVerse/CircuitVerseDocs#98]
#### I am submitting a -
* **Feature Request**

Real time Chat feature like a button named as `Open Chat`  needed in Official Documentation of CircuitVerse . When a student clicks on that button , it would automatically redirected to ongoing Gitter chat between mentor and various other GSOC students.

#### Screenshots (if relevant) -
![realtimechat](https://user-images.githubusercontent.com/28500944/55294609-bfcc4500-5421-11e9-89f4-01391e790939.png)

#### Are you working on this issue? (Yes/No)
Yes

**Comment by JoshHeng** [comment]
I don't think that this would be that beneficial, as we already have Discord and Slack servers.
